### ISSUE TITLE
Error Occurred

### ISSUE THREAD

**Issue by Venny2020** [Nuix/Export-Profile-Plus#11]
I tried running this report and the error I received is 

Performing setup: Item Set Duplicate Item Dates
Attaching scripted field: Item Set Duplicate Item Dates
Selected Items: 54830
Base Profile: Duplicates
Additional Fields:
	Item Set Duplicate Item Dates
Exporting...
Error occured in provided block:
(NoMethodError) undefined method `transform_values' for #<Hash:0x242b28df>
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `transform_values' for #<Hash:0x242b28df>
	at RUBY.block in (root)(C:\Users\a-reddyvx6\AppData\Roaming\Nuix\Scripts\ExportProfilePlusv1.28.0\ExportProfilePlus.nuixscript\ExportProfilePlus.rb:401)
	at RUBY.block in (root)(C:\Users\a-reddyvx6\AppData\Roaming\Nuix\Scripts\ExportProfilePlusv1.28.0\ExportProfilePlus.nuixscript\ExportProfilePlus.rb:388)
	at RUBY.<main>(C:\Users\a-reddyvx6\AppData\Roaming\Nuix\Scripts\ExportProfilePlusv1.28.0\ExportProfilePlus.nuixscript\ExportProfilePlus.rb:263)

**Comment by JuicyDragon** [comment]
Hello @Venny2020 what version of Nuix were you using when you received this error?  Looking at Ruby documentation the method `transform_values` looks valid so I'm not sure why it is reporting that it isn't.  The version of JRuby/Ruby may be different depending on the version of Nuix being used and I am wondering if perhaps this method was not present in a prior version of JRuby/Ruby.

**Comment by JuicyDragon** [comment]
Hello @Venny2020 I believe the issue has been figured out and fixed.  There was a method call being used that is not available in some older versions of Ruby, but is available in the version of Ruby bundled with more recent releases of Nuix.  The script has been updated to use a more backwards compatible equivalent in the code.  Please test the latest release and see if that solves your problems:

https://github.com/Nuix/Export-Profile-Plus/releases/tag/v1.28.1

**Comment by Venny2020** [comment]
Thanks Jason. The new version worked for me. I should have updated you
early. My apologies.

Thanks again!
